name: olx
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  json_annotation: ^2.4.0
  http: ^0.12.0
  dots_indicator: ^0.0.4
  shared_preferences: ^0.4.2
  carousel_slider: ^1.3.0
  dio: 3.0.0 #latest version
  image_picker: 0.6.2
  image_cropper: 1.1.0
  #google_maps_flutter: ^0.4.0
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.1.4+2
  google_map_location_picker: ^3.3.2
  intl: ^0.16.0
  rxdart: ^0.23.1
  bmprogresshud: ^0.0.5
  url_launcher: ^5.2.5
  progress_dialog: ^1.2.4
  rflutter_alert: ^1.0.2
  fluttertoast: ^4.0.1
  empty_widget: ^0.0.1-dev.1
  cached_network_image: ^2.3.2+1
  flutter_staggered_grid_view: ^0.3.4
  multi_image_picker: ^4.6.5
  flutter_share: ^1.0.5
  flutter_speed_dial: ^2.1.1
  ars_progress_dialog: ^0.1.2
  photo_view: 0.10.3
  animate_do: ^1.7.4
  webview_flutter: ^1.0.7
  shimmer: ^1.1.2
  auto_direction: any
  material_design_icons_flutter: any
  font_awesome_flutter: ^8.10.0
  device_preview: any
  flutter_zoom_drawer: ^1.0.5
  flutter_slidable: 0.5.7
  english_words: ^3.1.5
  flutter_range_slider: ^1.4.0
  flutter_xlider: ^3.4.0












dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  json_serializable: ^3.0.0
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - images/
    - assets/locale/locale_ar.json
    - assets/locale/locale_en.json
  fonts:
    - family: cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: messari
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
