import 'package:json_annotation/json_annotation.dart';
import 'package:olx/model/ads_detail.dart';
import 'package:olx/model/field_proprtires_entity.dart';
part 'edit_field_property.g.dart';


/// $id : "1"
/// AdData : {"$id":"2","Id":5173,"ArabicDescription":"test","EnglishDescription":"test","IsNogitable":false,"Price":23452523.0,"CategoryId":1274,"CategoryName":"??? ? ??????�","UserId":"5d8c9312-4f97-4cd1-bd74-a961353f668b","UserName":"1-01000000000","UserPhone":"01000000000","ArabicDescriptionUrl":"05125412","EnglishDescriptionUrl":"05125412","ArabicTitle":"TEst","EnglishTitle":"TEst","CountryId":1,"CountryNameEnglish":"Egypt","CountryNameArabic":"Egypt","LocationLatitude":0.0,"LocationLongtude":0.0,"IsDisplayed":true,"IsDeleted":true,"CreationTime":"2020-12-16T15:16:40.437","UpdateTime":null,"ViewCount":10,"CityId":1,"CityNameEnglish":"Cairo","CityNameArabic":"???????","StateId":135,"StateNameArabic":" ???? 15","StateNameEnglish":"15 May City","IsFavorite":false,"IsActive":true,"Advertisment_Specification":[{"$id":"3","Id":7469,"CategoryId":1274,"AdvertismentId":0,"CategorySpecificationId":2108,"NameEnglish":"Post type ","NameArabic":"??? ???????","CustomValue":null,"AdvertismentSpecificatioOptions":[{"$id":"4","Id":1108,"AdvertismentSpecificationId":null,"NameEnglish":"Demands","NameArabic":"?????","SpecificationOptionId":2165}],"CategorySpecificationVM":null,"AdvertismentSpecificationOptions":null},{"$id":"5","Id":7470,"CategoryId":1274,"AdvertismentId":0,"CategorySpecificationId":2112,"NameEnglish":"Furnished","NameArabic":"?????","CustomValue":null,"AdvertismentSpecificatioOptions":[{"$id":"6","Id":1109,"AdvertismentSpecificationId":null,"NameEnglish":"Yes","NameArabic":"???","SpecificationOptionId":2167}],"CategorySpecificationVM":null,"AdvertismentSpecificationOptions":null}],"AdvertismentImages":[{"$id":"7","Id":1761,"Url":"7aa3f821-04dc-4fc2-ae04-db41b883efa0.867446145.png","Size":26889.0,"IsImage":true,"CreationDate":"2020-12-16T15:16:23.42"},{"$id":"8","Id":1762,"Url":"5bd72e26-b6bf-404d-b4ce-801b02bcac0b.673083458.png","Size":29669.0,"IsImage":true,"CreationDate":"2020-12-16T15:16:23.797"}]}
/// CategorySpecification : [{"$id":"9","Id":2107,"CategoryId":1274,"CustomValue":null,"Value":null,"Required":true,"MuliSelect":false,"EnglishName":" Area  meter Sqeare","ArabicName":"???????  ? 2","IsCustomValue":null,"SpeceficationId":1,"Category":null,"SpecificationOptions":[]},{"$id":"10","Id":2108,"CategoryId":1274,"CustomValue":null,"Value":null,"Required":true,"MuliSelect":false,"EnglishName":"Post type ","ArabicName":"??? ???????","IsCustomValue":null,"SpeceficationId":2,"Category":null,"SpecificationOptions":[{"$id":"11","Id":2165,"IsSelected":true,"ArabicName":"?????","EnglishName":"Demands"},{"$id":"12","Id":2166,"IsSelected":false,"ArabicName":"?????","EnglishName":" For Sale"}]},{"$id":"13","Id":2109,"CategoryId":1274,"CustomValue":null,"Value":null,"Required":true,"MuliSelect":false,"EnglishName":"Number of floor","ArabicName":"??????","IsCustomValue":null,"SpeceficationId":1,"Category":null,"SpecificationOptions":[]},{"$id":"14","Id":2110,"CategoryId":1274,"CustomValue":null,"Value":null,"Required":true,"MuliSelect":false,"EnglishName":"Number of rooms","ArabicName":"??? ?????","IsCustomValue":null,"SpeceficationId":1,"Category":null,"SpecificationOptions":[]},{"$id":"15","Id":2111,"CategoryId":1274,"CustomValue":null,"Value":null,"Required":true,"MuliSelect":false,"EnglishName":"Number of bathrooms","ArabicName":"??? ????????","IsCustomValue":null,"SpeceficationId":1,"Category":null,"SpecificationOptions":[]},{"$id":"16","Id":2112,"CategoryId":1274,"CustomValue":null,"Value":null,"Required":true,"MuliSelect":false,"EnglishName":"Furnished","ArabicName":"?????","IsCustomValue":null,"SpeceficationId":2,"Category":null,"SpecificationOptions":[{"$id":"17","Id":2167,"IsSelected":true,"ArabicName":"???","EnglishName":"Yes"},{"$id":"18","Id":2168,"IsSelected":false,"ArabicName":"??","EnglishName":"No"}]},{"$id":"19","Id":2113,"CategoryId":1274,"CustomValue":null,"Value":null,"Required":false,"MuliSelect":false,"EnglishName":"Age of Building","ArabicName":"??? ??????","IsCustomValue":null,"SpeceficationId":1,"Category":null,"SpecificationOptions":[]},{"$id":"20","Id":2114,"CategoryId":1274,"CustomValue":null,"Value":null,"Required":false,"MuliSelect":true,"EnglishName":"Amenities","ArabicName":"????? ??????","IsCustomValue":null,"SpeceficationId":2,"Category":null,"SpecificationOptions":[{"$id":"21","Id":2169,"IsSelected":false,"ArabicName":"????","EnglishName":"Air Conditioning"},{"$id":"22","Id":2170,"IsSelected":false,"ArabicName":"????","EnglishName":"Elevator"},{"$id":"23","Id":2171,"IsSelected":false,"ArabicName":"????","EnglishName":"Garage Parking"},{"$id":"24","Id":2172,"IsSelected":false,"ArabicName":"???? ????","EnglishName":"Watertank"},{"$id":"25","Id":2173,"IsSelected":false,"ArabicName":"???? ???","EnglishName":"Security"}]}]
@JsonSerializable()
class EditFieldProperty {
  String $id;
  AdsDetail AdData;
  List<FieldProprtiresEntity> CategorySpecification;
  EditFieldProperty({this.$id,this.AdData,this.CategorySpecification});

  factory EditFieldProperty.fromJson(Map<String, dynamic> json) => _$EditFieldPropertyFromJson(json);

}

